### ISSUE TITLE
Do not support the data if too large or too small. For Example, a,z,y(A,Z,Y)

### ISSUE THREAD

**Issue by Leo452379** [NEVSTOP-LAB/CSM-API-String-Arguments-Support#35]

**Comment by nevstop** [comment]
@Leo452379  已修复。

**Comment by nevstop** [comment]
![image](https://github.com/NEVSTOP-LAB/CSM-API-String-Arguments-Support/assets/8196752/68d69669-3e19-408e-b880-d45e1115746c)
