### ISSUE TITLE
Issue with nested array

### ISSUE THREAD

**Issue by hautale** [NEVSTOP-LAB/CSM-API-String-Arguments-Support#58]
Convert API String arguments to data, does not work if array contains cluster with array.

**Comment by nevstop** [comment]
Hi @hautale, thank you for the reminder. I am aware of this issue and will address it after passing those busy days. Please continue to follow the thread for updates once it's resolved.

**Comment by nevstop** [comment]
![image](https://github.com/user-attachments/assets/be05b021-8cb6-4170-9c84-dd21c0c3fd04)

**Comment by nevstop** [comment]
@hautale I have fixed this issue and update the package to vipm.io in September's release. You could see the screenshot above. Let me know your thought. If you find CSM and this repo useful to you, please star it. Any feedback is welcomed. Thanks.
